# slack id
slack_id: 'your webhook url'

# arxivの学問領域の指定
subject:
  - 'physics.comp-ph'
  - 'physics.data-an'
  - 'cond-mat.dis-nn'
  - 'cond-mat.stat-mech'
  - 'cs.AI'
  - 'cs.CC'
  - 'cs.DS'
  - 'cs.LG'
